website/author/views.py
from flask import Blueprint, render_template
from flask_login import login_required

from ..models import Author

author = Blueprint("author", __name__, url_prefix="/authors", static_folder="../static")


@author.route("/")
@login_required
def author_list():
    authors = Author.query.all()
    return render_template(
        "authors/list.html",
        authors=authors
    )

website/index/views.py
from flask import Blueprint, render_template

index = Blueprint("index", __name__, url_prefix="/", static_folder="../static")


@index.route("/")
def main_page():
    return render_template(
        "base.html"
    )

website/report/views.py
from flask import Blueprint, render_template

report = Blueprint("report", __name__, url_prefix="/reports", static_folder="../static")


@report.route("/")
def report_list():
    return render_template(
        "base.html",
        reports=[1, 231, 4]
    )

website/user/views.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user, login_user
from werkzeug.exceptions import NotFound
from werkzeug.security import generate_password_hash

from ..extensions import db
from ..forms.user import UserRegisterForm
from ..models import User

user = Blueprint("user", __name__, url_prefix="/users", static_folder="../static")
USERS = {
    1: {"name": "Ivan"},
    2: {"name": "Jon"},
    3: {"name": "Mary"}
}


@user.route("register", methods=["POST", "GET"])
def register_user():
    if current_user.is_authenticated:
        return redirect(url_for("user.profile", pk=current_user.id))
    form = UserRegisterForm(request.form)
    errors = []
    if request.method == "POST" and form.validate_on_submit():
        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append("email not uniq")
            return render_template("users/register.html", form=form, errors=errors)
        _user = User(email=form.email.data,
                     password=generate_password_hash(form.password.data),
                     first_name=form.first_name.data,
                     last_name=form.last_name.data)
        db.session.add(_user)
        db.session.commit()

        login_user(_user)
    return render_template("users/register.html", form=form, errors=errors)


@user.route("/")
@login_required
def user_list():
    users = User.query.all()
    return render_template(
        "users/list.html",
        users=users
    )


@user.route("/<int:pk>")
@login_required
def profile(pk: int):
    _user = User.query.filter_by(id=pk).one_or_none()
    if _user is None:
        raise NotFound("User id:{}, not found".format(pk))
    return render_template(
        "users/details.html",
        user=_user
    )


def get_user_name(pk: int):
    if pk in USERS:
        user_name = USERS[pk]["name"]
    else:
        raise NotFound("User id:{}, not found".format(pk))
    return user_name

website/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}{% endblock %}
    </title>
    {% include "navbar.html" %}
      {% block css %}
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    {% endblock %}
  </head>
  <body>
    <div class="container">
      {% block body %}{% endblock %}
    </div>
    {% block js %}
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"  ></script>
    {% endblock %}
  </body>
</html>

website/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('index.main_page') }}">GB Flask</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('index.main_page') }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('user.user_list') }}">Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('author.author_list') }}">Authors</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('article.article_list') }}">Articles</a>
        </li>
        {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('article.create_article_form') }}">Create article</a>
          </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('report.report_list') }}">Reports</a>
        </li>
        {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('auth.logout') }}">Logout</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('auth.login') }}">Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>